server:
  port: 8202
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-api
  cloud:
    discovery:
      client:
        simple:
          instances:
            "[platform-api]":
              - host: localhost
                port: 8201



